### ISSUE TITLE
feat: Firefox support

### ISSUE THREAD

**Issue by sammcj** [giosilvi/GPT-Prompter#10]
It would be awesome if this extension had Firefox support - it's really great!

**Comment by giosilvi** [comment]
Thanks for the comment! I have to admit this is my first ever chrome extension, and I don`t know how it works for Firefox. As soon as it reaches a mature version (I think a few months more of experimenting) I will look into porting it to Firefox too.

**Comment by Stvad** [comment]
@giosilvi they have a compatible API, so usually most of the porting consists substituting `chrome.*` calls to `browser.*` calls (with https://github.com/mozilla/webextension-polyfill installed) to get a cross-browser support up and running. there are a bunch of cross-browser extension templates out there that can serve as a good example)

**Comment by giosilvi** [comment]
@Stvad thanks for the info! I'll take a look at it and make the implementation in the next month or so...

**Comment by giosilvi** [comment]
Hi @Stvad  and @sammcj, I published the extension on Firefox as well! There was some modification involved, mostly on the manifest.json. At the moment, there is a bit of an unusual behavior when first loading a webpage, where one may need to reload the page to make the extension work. I'll try to fix that in the next days, but for the rest, everything seems to work just fine. You can find it here: https://addons.mozilla.org/en-GB/firefox/addon/gpt-prompter/

**Comment by sammcj** [comment]
Oh wow that's fantastic news! Thank you so much, I'll test it out this week.

**Comment by giosilvi** [comment]
I reopened the issue cause I saw some strange behavior on Firefox with some elements of Outlook when the extension is enabled. Need to investigate, the same situation on Chrome show now issue.
