### ISSUE TITLE
text-davinci-003 Support?

### ISSUE THREAD

**Issue by voidxd** [giosilvi/GPT-Prompter#13]
I really like your extension. Thank you so much for your work.

You've probably seen news of the new model, text-davinci-003. I've tried adding it myself, but I think I messed something up and the extension stopped working.

Any plans to add it anytime soon?

Thank you!

EDIT: Oh, I see you're already at it. Thanks again for this extension!

**Comment by giosilvi** [comment]
You are welcome!
