### ISSUE TITLE
where do I paste in the API key?

### ISSUE THREAD

**Issue by alok** [giosilvi/GPT-Prompter#14]
I see no extension option page and right click menu doesn't give a place to put it that worked

**Comment by giosilvi** [comment]
Hi @alok , you can find it in the icon of the extension. In the upper right side of chrome you can find the (pinned) icons of extension of chrome. There is also an icon shaped like a puzzle piece that show the remaining extension unpinned, the first time you installed it will be there unpinned. Click on it and you will find easily where to insert the API key
