### ISSUE TITLE
[Bug] Doesn't work in chrome pdf viewer when opening local file

### ISSUE THREAD

**Issue by xosmig** [giosilvi/GPT-Prompter#15]
Thanks a lot for the amazing extension!

I've noticed that it doesn't seem to work when opening a PDF file from the local computer using the Chrome built-in PDF viewer, but it does work when opening a PDF from the Internet (e.g., an arXiv paper).

Other extensions (e.g., [save to pocket](https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj)) work in both cases, which suggests that it must be possible to fix this behaviour.

**Comment by xosmig** [comment]
Also, doesn't work on the "History of Your Prompts and Cost" page from the extension itself.

**Comment by giosilvi** [comment]
Hi, I fixed the issue ( in the next version 0.0.0.8) with local files like pdf.  But regarding the History page, I didn`t manage to make it work so far. The new version is now in review and should be available tomorrow at the latest.

**Comment by giosilvi** [comment]
Hi @xosmig , I forgot to add that the user needs to allow the extension access to local files manually. 
From the the Extension page, GPT-Prompter -> Details -> Allow access to file URLs.
