### ISSUE TITLE
Bug: Typing in promoter popup UI infers with web app shortcuts

### ISSUE THREAD

**Issue by cquanu** [giosilvi/GPT-Prompter#23]
## Summary
When typing in the promoter popup UI, it is inferring with web app shortcuts instead of what is being typed.

## Steps to Reproduce
1. Go to the promoter popup UI
2. Begin typing in the focus input
3. App behind the prompter pop-up UI is affected by the keystroke

## Expected Behavior
What is being typed should appear in the popup text field, the website behind the popup UI should ignore the keystroke.

## Environment
**Browser - Chrome** 

https://user-images.githubusercontent.com/16508884/216566520-f88448e3-e2fd-427c-9a6c-cebda6cc0478.mp4
https://www.keyboardtester.com/tester.html

**Comment by giosilvi** [comment]
HI @cquanu, very interesting, thanks! I thought I had solved this particular issue already. I noticed this behavior before when typing in the popup while on a website like Github (there for example the key "s" activated the search).
Will investigate further.

**Comment by cquanu** [comment]
Thanks @giosilvi, hope this will be fixed soon :)

**Comment by giosilvi** [comment]
Hi @cquanu, the issue has been fixed in the latest version (is already out). It turned out the propagation of events where just blocked for keydown but not keyup event. Now is fixed.
