### ISSUE TITLE
Error if selecting code segment.

### ISSUE THREAD

**Issue by sting8k** [giosilvi/GPT-Prompter#26]
When selecting a code segment on GitHub (for example), then select a prompt, it may cause an error like the following: 
[https://imgur.com/tFnobdD](https://imgur.com/tFnobdD)

It seems that some of the characters selected may be the cause of this error. 

Example selected text: [mongodb.js](https://raw.githubusercontent.com/snoopysecurity/Vulnerable-Code-Snippets/master/NoSQL%20Injection/mongodb.js)

**Comment by giosilvi** [comment]
Hi @sting8k, I have found the issue, and will soon publish a fix for it.
Thanks, for the feedback!

**Comment by giosilvi** [comment]
Hi @sting8k the new version 0.0.3.3. should have that particular issue fixed.

**Comment by sting8k** [comment]
> Hi @sting8k the new version 0.0.3.3. should have that particular issue fixed.

That's cool 👍
