### ISSUE TITLE
[Bug] backslash is interpreted as a special character

### ISSUE THREAD

**Issue by xosmig** [giosilvi/GPT-Prompter#28]
The backslashes ("\\") are interpreted as special characters, resulting in unexpected behaviour.

E.g., `hello, \text{world}` is interpreted as `hello, [tab symbol]ext{world}` and on something like `hello, \world` it simply doesn't work as it tries to interpret `\w` as an escape sequence.

This makes it impossible to use, for example, when editing latex in [overleaf](https://www.overleaf.com/).

**Comment by gsilviHQS** [comment]
Hi @xosmig I just released the new version (make sure to update it to 0.0.3.3). I test your example and seems to be fixed.
Please take a look and let me know if now works.

**Comment by xosmig** [comment]
Seems to work, thank you!
