### ISSUE TITLE
Option to disable original text display

### ISSUE THREAD

**Issue by younyokel** [giosilvi/GPT-Prompter#8]
Please make a option to turn off original text after the new update (v 0.0.0.2).

**Comment by giosilvi** [comment]
I was thinking about it. Would you prefer a global option or a button in each popup to selective hide the original text?

**Comment by younyokel** [comment]
> I was thinking about it. Would you prefer a global option or a button in each popup to selective hide the original text?

I personally would like a global option so that there is no unnecessary stuff when the popup appears. But the button to disable the original text can also be "hidden" inside the popup, if it does not interfere and the option itself is remembered globally when used.

**Comment by giosilvi** [comment]
I have submitted a new version which by default keep the upper part op the popup (the one with the prompt) as one line height. But with double click on it to expand it. In the future I will add an extra page with advanced setting including the option to keep it one-line or expanded as deafult
